exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex("chatrooms")
    .del()
    .then(function() {
      // Inserts seed entries
      return knex("chatrooms").insert([
        {
          name: "Los Angeles, CA",
          user_id: 1,
          permanent: false,
          description: "A chatroom for Los Angeles, California",
          chatroom_url: "sendbird_open_channel_52771_74cbb1034648504d88f2e1ff335cf2c86b3fd767",
          chatroom_type: "big city",
          img_url: "https://sendbird.com/main/img/cover/cover_01.jpg",
          longitude: -118.243683, 
          latitude: 34.052235
        },
        {
          name: "Westerly, RI",
          user_id: 2,
          permanent: true,
          description: "A chatroom for Westerly, Rhode Island",
          chatroom_url: "sendbird_open_channel_52771_bb3423f848cba53c24d267146acc278808136b21",
          chatroom_type: "town",
          img_url: "https://sendbird.com/main/img/cover/cover_02.jpg",
          longitude: -71.807301, 
          latitude: 41.371804
        },
        {
          name: "Atlanta, GA",
          user_id: 2,
          permanent: true,
          description: "A chatroom for Atlanta, Georgia",
          chatroom_url: "sendbird_open_channel_52771_cf7404b157106ab6aabf9240fdbc5feacc0f537f",
          chatroom_type: "big city",
          img_url: "https://sendbird.com/main/img/cover/cover_03.jpg",
          longitude: -84.386330, 
          latitude: 33.753746
        },
        {
          name: "San Francisco, CA",
          user_id: 1,
          permanent: false,
          description: "A chatroom for San Francisco, CA",
          chatroom_url: "sendbird_open_channel_52771_a06b52701b32c1da7a1286f6b5b8f0de3f4cf7d2",
          chatroom_type: "big city",
          img_url: "https://sendbird.com/main/img/cover/cover_04.jpg",
          longitude: -122.431297, 
          latitude: 37.773972
        },
        {
          name: "Detroit, MI",
          user_id: 3,
          permanent: false,
          description: "A chatroom for Detroit, MI",
          chatroom_url: "sendbird_open_channel_52771_86113d4395145363821c384a131783042beae907",
          chatroom_type: "big city",
          img_url: "https://sendbird.com/main/img/cover/cover_05.jpg",
          longitude: -83.045753, 
          latitude: 42.331429
        },
        {
          name: "Toronto, ON",
          user_id: 3,
          permanent: false,
          description: "A chatrooom about Toronto, ON",
          chatroom_url: "sendbird_open_channel_52771_86e7888ea74da04c2c221353b90ac8923cb1f98b",
          chatroom_type: "big city",
          img_url: "https://sendbird.com/main/img/cover/cover_06.jpg",
          longitude: -79.411079, 
          latitude: 46.761539
        },
        {
          name: "Denver, CO",
          user_id: 3,
          permanent: false,
          description: "A chatroom for Denver, CO",
          chatroom_url: "sendbird_open_channel_52771_64345b8888088647b8e895bfbdd98be7cb3489df",
          chatroom_type: "big city",
          img_url: "https://sendbird.com/main/img/cover/cover_07.jpg",
          longitude: -104.991531, 
          latitude: 39.742043
        },
        {
          name: "Austin, TX",
          user_id: 3,
          permanent: false,
          description: "A chatroom for Austin, TX",
          chatroom_url: "sendbird_open_channel_52771_fc33724c7336ef4f76b1fc7fbe5d0787fa9f5733",
          chatroom_type: "big city",
          img_url: "https://sendbird.com/main/img/cover/cover_08.jpg",
          longitude: -97.7430608, 
          latitude: 30.267153
        },
        {
          name: "Dallas, TX",
          user_id: 3,
          permanent: false,
          description: "A chatroom for Dallas, TX",
          chatroom_url: "sendbird_open_channel_52771_f9cfdd4c0f9767ebd40a8709a86e745093d06015",
          chatroom_type: "big city",
          img_url: "https://sendbird.com/main/img/cover/cover_09.jpg",
          longitude: -97.040443, 
          latitude: 32.897480
        },
        {
          name: "Fenway Park",
          user_id: 3,
          permanent: false,
          description: "Welcome to Fenway Park!",
          chatroom_url: "sendbird_open_channel_52771_afa5f77b4e4e4d5a471bb7c9666047bad5f97880",
          chatroom_type: "stadium",
          img_url: "https://sendbird.com/main/img/cover/cover_01.jpg",
          longitude: -71.095764, 
          latitude: 42.346268
        },
        {
          name: "Boston, MA",
          user_id: 3,
          permanent: false,
          description: "A chatroom for Boston, MA",
          chatroom_url: "sendbird_open_channel_52771_84a44fb5f0fadf955c3eab7ef4510c704852aa8e",
          chatroom_type: "big city",
          img_url: "https://sendbird.com/main/img/cover/cover_02.jpg",
          longitude: -71.057083, 
          latitude: 42.361145
        },
        {
          name: "New York, NY",
          user_id: 3,
          permanent: false,
          description: "A chatroom for NYC",
          chatroom_url: "sendbird_open_channel_52771_537d5b9296f52fe6dedfba8714dfa8679314560c",
          chatroom_type: "big city",
          img_url: "https://sendbird.com/main/img/cover/cover_03.jpg",
          longitude: -73.935242, 
          latitude: 40.730610
        },
        {
          name: "San Diego, CA",
          user_id: 3,
          permanent: false,
          description: "A chatroom for San Diego, CA",
          chatroom_url: "sendbird_open_channel_52771_c06a0b8cce72eb94999d1fbfbb5b51fcd8cd140c",
          chatroom_type: "big city",
          img_url: "https://sendbird.com/main/img/cover/cover_04.jpg",
          longitude: -117.161087, 
          latitude: 32.715736
        },
        {
          name: "General Channel",
          user_id: 3,
          permanent: false,
          description: "A chat for all to speak",
          chatroom_url: "sendbird_open_channel_52771_f69e5cfb8ea5204ea44f8088059bcb45dab82f13",
          chatroom_type: "worldwide",
          img_url: "https://sendbird.com/main/img/cover/cover_05.jpg",
          longitude: -101.249726, 
          latitude: 40.681892
        },
        {
          name: "Providence, RI",
          user_id: 2,
          permanent: true,
          description: "A chatroom for Providence, Rhode Island",
          chatroom_url: "sendbird_open_channel_52771_9b798539b4dad0f9d953c6eac40f5d29af1328a3",
          chatroom_type: "town",
          img_url: "https://sendbird.com/main/img/cover/cover_06.jpg",
          longitude: -71.418884, 
          latitude: 41.825226
        },
        {
          name: "East Beach, Westerly, RI",
          user_id: 2,
          permanent: true,
          description: "A chatroom for East Beach in Westerly, Rhode Island",
          chatroom_url: "sendbird_open_channel_52771_03419f5e356e0cbef3ed2ca228c97c82bb018414",
          chatroom_type: "beach",
          img_url: "https://sendbird.com/main/img/cover/cover_07.jpg",
          longitude: -71.850946, 
          latitude: 41.309600
        },
        {
          name: "Orlando, FL",
          user_id: 2,
          permanent: true,
          description: "A chatroom for Orlando, FL",
          chatroom_url: "sendbird_open_channel_52771_6d19c3ec908ebce79ec7d31ca29584dd584b84f9",
          chatroom_type: "big city",
          img_url: "https://sendbird.com/main/img/cover/cover_08.jpg",
          longitude: -81.379234, 
          latitude: 28.538336
        },
        {
          name: "Miami, FL",
          user_id: 2,
          permanent: true,
          description: "A chatroom for Miami, FL",
          chatroom_url: "sendbird_open_channel_52771_86ba92cce73c454a0e5eedac375b521e0467f10f",
          chatroom_type: "big city",
          img_url: "https://sendbird.com/main/img/cover/cover_09.jpg",
          longitude: -80.191788, 
          latitude: 25.761681
        },
        {
          name: "Tampa, FL",
          user_id: 2,
          permanent: true,
          description: "A chatroom for Tampa, FL",
          chatroom_url: "sendbird_open_channel_52771_7cf5eb21ea76c67f09516d152620b7654cfec632",
          chatroom_type: "big city",
          img_url: "https://sendbird.com/main/img/cover/cover_01.jpg",
          longitude: -82.452606, 
          latitude: 27.964157
        },
        {
          name: "Chicago, IL",
          user_id: 2,
          permanent: true,
          description: "A chatroom for Chicago, IL",
          chatroom_url: "sendbird_open_channel_52771_928c6c34611eeb8ff9b0e8cc7017075b416dc12c",
          chatroom_type: "big city",
          img_url: "https://sendbird.com/main/img/cover/cover_02.jpg",
          longitude: -87.623177, 
          latitude: 41.881832
        },
        {
          name: "Houston, TX",
          user_id: 2,
          permanent: true,
          description: "A chatroom for Houston, TX",
          chatroom_url: "sendbird_open_channel_52771_928c6c34611eeb8ff9b0e8cc7017075b416dc12c",
          chatroom_type: "big city",
          img_url: "https://sendbird.com/main/img/cover/cover_03.jpg",
          longitude: -95.358421, 
          latitude: 29.749907
        },
        {
          name: "Philadelphia, PA",
          user_id: 2,
          permanent: true,
          description: "A chatroom for Philadelphia, PA",
          chatroom_url: "sendbird_open_channel_52771_7534af94922fcd54deacdc2b5f3f40d207fc1eb1",
          chatroom_type: "big city",
          img_url: "https://sendbird.com/main/img/cover/cover_04.jpg",
          longitude: -75.165222, 
          latitude: 39.952583
        },
        {
          name: "Phoenix, AZ",
          user_id: 2,
          permanent: true,
          description: "A chatroom for Phoenix, AZ",
          chatroom_url: "phoenix",
          chatroom_type: "big city",
          img_url: "https://sendbird.com/main/img/cover/cover_05jpg",
          longitude: -112.074036,
          latitude: 33.448376
        },
        {
          name: "San Antonio, TX",
          user_id: 2,
          permanent: true,
          description: "A chatroom for San Antonio, TX",
          chatroom_url: "san_antonio",
          chatroom_type: "big city",
          img_url: "https://sendbird.com/main/img/cover/cover_06jpg",
          longitude: -98.491142,
          latitude: 29.424349
        },
        {
          name: "San Jose, CA",
          user_id: 2,
          permanent: true,
          description: "A chatroom for San Jose, CA",
          chatroom_url: "san_jose",
          chatroom_type: "big city",
          img_url: "https://sendbird.com/main/img/cover/cover_07jpg",
          longitude: -121.893028,
          latitude: 37.335480
        },
        {
          name: "Jacksonville, FL",
          user_id: 2,
          permanent: true,
          description: "A chatroom for Jacksonville, FL",
          chatroom_url: "jacksonville",
          chatroom_type: "big city",
          img_url: "https://sendbird.com/main/img/cover/cover_08jpg",
          longitude: -81.655647,
          latitude: 30.332184
        },
        {
          name: "Indianapolis, IN",
          user_id: 2,
          permanent: true,
          description: "A chatroom for Indianapolis, IN",
          chatroom_url: "indy",
          chatroom_type: "big city",
          img_url: "https://sendbird.com/main/img/cover/cover_09jpg",
          longitude: -86.120999516,
          latitude: 39.802830122
        },
        {
          name: "Columbus, OH",
          user_id: 2,
          permanent: true,
          description: "A chatroom for Columbus, OH",
          chatroom_url: "columbus",
          chatroom_type: "big city",
          img_url: "https://sendbird.com/main/img/cover/cover_01jpg",
          longitude: -82.99879,
          latitude: 39.96118
        },
        {
          name: "Charlotte, NC",
          user_id: 2,
          permanent: true,
          description: "A chatroom for Charlotte, NC",
          chatroom_url: "charlotte",
          chatroom_type: "big city",
          img_url: "https://sendbird.com/main/img/cover/cover_02jpg",
          longitude: -80.843124,
          latitude: 35.227085
        },
        {
          name: "El Paso, TX",
          user_id: 2,
          permanent: true,
          description: "A chatroom for El Paso, TX",
          chatroom_url: "el_paso",
          chatroom_type: "big city",
          img_url: "https://sendbird.com/main/img/cover/cover_03jpg",
          longitude: -80.843124,
          latitude: 35.227085
        },
        {
          name: "Seattle, WA",
          user_id: 2,
          permanent: true,
          description: "A chatroom for Seattle, WA",
          chatroom_url: "seattle",
          chatroom_type: "big city",
          img_url: "https://sendbird.com/main/img/cover/cover_04jpg",
          longitude: -122.335167,
          latitude: 47.608013
        },
        {
          name: "Washington, DC",
          user_id: 2,
          permanent: true,
          description: "A chatroom for Washington, DC",
          chatroom_url: "wash_dc",
          chatroom_type: "town",
          img_url: "https://sendbird.com/main/img/cover/cover_05jpg",
          longitude: 	-77.009003,
          latitude: 38.889931
        },
        {
          name: "Memphis, TN",
          user_id: 2,
          permanent: true,
          description: "A chatroom for Memphis, TN",
          chatroom_url: "memphis",
          chatroom_type: "big city",
          img_url: "https://sendbird.com/main/img/cover/cover_06jpg",
          longitude: -89.969329456,
          latitude: 35.117166198
        },
        {
          name: "Nashville, TN",
          user_id: 2,
          permanent: true,
          description: "A chatroom for Nashville, TN",
          chatroom_url: "nashville",
          chatroom_type: "big city",
          img_url: "https://sendbird.com/main/img/cover/cover_07jpg",
          longitude: -86.767960,
          latitude: 36.174465
        },
        {
          name: "Baltimore, MD",
          user_id: 2,
          permanent: true,
          description: "A chatroom for Baltimore, MD",
          chatroom_url: "baltimore",
          chatroom_type: "big city",
          img_url: "https://sendbird.com/main/img/cover/cover_08jpg",
          longitude: -76.609383,
          latitude: 39.299236
        },
        {
          name: "Oklahoma City, OK",
          user_id: 2,
          permanent: true,
          description: "A chatroom for Oklahoma City, OK",
          chatroom_url: "oklahoma_city",
          chatroom_type: "big city",
          img_url: "https://sendbird.com/main/img/cover/cover_09jpg",
          longitude: -97.508469,
          latitude: 35.481918
        },
        {
          name: "Portland, OR",
          user_id: 2,
          permanent: true,
          description: "A chatroom for Portland, OR",
          chatroom_url: "portland_or",
          chatroom_type: "big city",
          img_url: "https://sendbird.com/main/img/cover/cover_01jpg",
          longitude: -122.676483,
          latitude: 45.523064
        },
        {
          name: "Las Vegas, NV",
          user_id: 2,
          permanent: true,
          description: "A chatroom for Las Vegas, NV",
          chatroom_url: "las_vegas",
          chatroom_type: "big city",
          img_url: "https://sendbird.com/main/img/cover/cover_02jpg",
          longitude: 	-115.172813,
          latitude: 36.114647
        },
        {
          name: "Louisville, KY",
          user_id: 2,
          permanent: true,
          description: "A chatroom for Louisville, KY",
          chatroom_url: "louisville",
          chatroom_type: "big city",
          img_url: "https://sendbird.com/main/img/cover/cover_03jpg",
          longitude: 	-85.764771,
          latitude: 38.328732
        },
        {
          name: "Milwaukee, WI",
          user_id: 2,
          permanent: true,
          description: "A chatroom for Milwaukee, WI",
          chatroom_url: "milwaukee",
          chatroom_type: "big city",
          img_url: "https://sendbird.com/main/img/cover/cover_04jpg",
          longitude: 	-87.906471,
          latitude: 43.038902
        },
        {
          name: "Albuquerque, NM",
          user_id: 2,
          permanent: true,
          description: "A chatroom for Albuquerque, NM",
          chatroom_url: "albuquerque",
          chatroom_type: "big city",
          img_url: "https://sendbird.com/main/img/cover/cover_05jpg",
          longitude: 	-106.629181,
          latitude: 35.106766
        },
        {
          name: "Tucson, AZ",
          user_id: 2,
          permanent: true,
          description: "A chatroom for Tucson, AZ",
          chatroom_url: "tucson",
          chatroom_type: "big city",
          img_url: "https://sendbird.com/main/img/cover/cover_06jpg",
          longitude: 	-110.911789,
          latitude: 32.253460
        },
        {
          name: "Fresno, CA",
          user_id: 2,
          permanent: true,
          description: "A chatroom for Fresno, CA",
          chatroom_url: "fresno",
          chatroom_type: "town",
          img_url: "https://sendbird.com/main/img/cover/cover_07jpg",
          longitude: 	-119.772591,
          latitude: 36.746841
        },
        {
          name: "Sacramento, CA",
          user_id: 2,
          permanent: true,
          description: "A chatroom for Sacramento, CA",
          chatroom_url: "sacramento",
          chatroom_type: "town",
          img_url: "https://sendbird.com/main/img/cover/cover_08jpg",
          longitude: 	-121.478851,
          latitude: 38.575764
        },
        {
          name: "Long Beach, CA",
          user_id: 2,
          permanent: true,
          description: "A chatroom for Long Beach, CA",
          chatroom_url: "long_beach",
          chatroom_type: "town",
          img_url: "https://sendbird.com/main/img/cover/cover_09jpg",
          longitude: 	-118.193741,
          latitude: 33.770050
        },
        {
          name: "Kansas City, MO",
          user_id: 2,
          permanent: true,
          description: "A chatroom for Kansas City, MO",
          chatroom_url: "kansas_city_mo",
          chatroom_type: "town",
          img_url: "https://sendbird.com/main/img/cover/cover_01jpg",
          longitude: 	-94.581078,
          latitude: 39.110298
        },
        {
          name: "Mesa, AZ",
          user_id: 2,
          permanent: true,
          description: "A chatroom for Mesa, AZ",
          chatroom_url: "mesa",
          chatroom_type: "town",
          img_url: "https://sendbird.com/main/img/cover/cover_02jpg",
          longitude: 	-111.833267,
          latitude: 33.424564
        },
        {
          name: "Virginia Beach, VA",
          user_id: 2,
          permanent: true,
          description: "A chatroom for Virginia Beach, VA",
          chatroom_url: "virginia_beach",
          chatroom_type: "town",
          img_url: "https://sendbird.com/main/img/cover/cover_03jpg",
          longitude: 	-76.015778,
          latitude: 36.863140
        },
        {
          name: "Omaha, NE",
          user_id: 2,
          permanent: true,
          description: "A chatroom for Omaha, NE",
          chatroom_url: "omaha",
          chatroom_type: "town",
          img_url: "https://sendbird.com/main/img/cover/cover_04jpg",
          longitude: 	-95.995102,
          latitude: 41.257160
        },
        {
          name: "Colorado Springs, CO",
          user_id: 2,
          permanent: true,
          description: "A chatroom for Colorado Springs, CO",
          chatroom_url: "co_springs",
          chatroom_type: "town",
          img_url: "https://sendbird.com/main/img/cover/cover_05jpg",
          longitude: 	-104.800644,
          latitude: 38.846127
        },
        {
          name: "Raleigh, NC",
          user_id: 2,
          permanent: true,
          description: "A chatroom for Raleigh, NC",
          chatroom_url: "raleigh",
          chatroom_type: "big city",
          img_url: "https://sendbird.com/main/img/cover/cover_06jpg",
          longitude: 	-78.644257,
          latitude: 35.787743
        },
        {
          name: "Minneapolis, MN",
          user_id: 2,
          permanent: true,
          description: "A chatroom for Minneapolis, MN",
          chatroom_url: "minneapolis",
          chatroom_type: "big city",
          img_url: "https://sendbird.com/main/img/cover/cover_07jpg",
          longitude: 	-93.258133,
          latitude: 44.986656
        },
        {
          name: "Tulsa, OK",
          user_id: 2,
          permanent: true,
          description: "A chatroom for Tulsa, OK",
          chatroom_url: "tulsa",
          chatroom_type: "big city",
          img_url: "https://sendbird.com/main/img/cover/cover_08jpg",
          longitude: 	-95.992775,
          latitude: 36.153980
        },
        {
          name: "Cleveland, OH",
          user_id: 2,
          permanent: true,
          description: "A chatroom for Cleveland, OH",
          chatroom_url: "cleveland",
          chatroom_type: "big city",
          img_url: "https://sendbird.com/main/img/cover/cover_09jpg",
          longitude: 	-81.681290,
          latitude: 41.505493
        },
        {
          name: "New Orleans, LA",
          user_id: 2,
          permanent: true,
          description: "A chatroom for New Orleans, LA",
          chatroom_url: "new_orleans",
          chatroom_type: "big city",
          img_url: "https://sendbird.com/main/img/cover/cover_01jpg",
          longitude: 	-90.071533,
          latitude: 29.951065
        },
        {
          name: "Wichita, KS",
          user_id: 2,
          permanent: true,
          description: "A chatroom for Wichita, KS",
          chatroom_url: "wichita",
          chatroom_type: "big city",
          img_url: "https://sendbird.com/main/img/cover/cover_02jpg",
          longitude: 	-97.314835,
          latitude: 37.697948
        },
        {
          name: "Jackson Hole, WY",
          user_id: 2,
          permanent: true,
          description: "A chatroom for Jackson Hole, WY",
          chatroom_url: "jackson_hole",
          chatroom_type: "big city",
          img_url: "https://sendbird.com/main/img/cover/cover_03jpg",
          longitude: 	-110.83333,
          latitude: 43.5166646
        },
        {
          name: "Helena, MT",
          user_id: 2,
          permanent: true,
          description: "A chatroom for Helena, MT",
          chatroom_url: "helena",
          chatroom_type: "rural city",
          img_url: "https://sendbird.com/main/img/cover/cover_03jpg",
          longitude: 	-112.534775,
          latitude: 46.003822
        },
        {
          name: "Boise, ID",
          user_id: 2,
          permanent: true,
          description: "A chatroom for Boise, ID",
          chatroom_url: "boise",
          chatroom_type: "rural city",
          img_url: "https://sendbird.com/main/img/cover/cover_03jpg",
          longitude: 	-116.215019,
          latitude: 43.618881
        },
         


      ]);
    });
};
